version: '3.8'

services:
  postgres-authuser:
    image: postgres:15
    container_name: postgres-authuser
    restart: always
    environment:
      POSTGRES_USER: eaduser
      POSTGRES_PASSWORD: eadpass
      POSTGRES_DB: ead-authuser
    ports:
      - "5433:5432"
    volumes:
      - postgres_authuser_data:/var/lib/postgresql/data
    networks:
      - ead-network

volumes:
  postgres_authuser_data:

networks:
  ead-network:
    driver: bridge
