server:
  port: 8761

spring:
  application:
    name: ead-service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    hostname: localhost
  eureka-server:
    enable-self-preservation: false