server:
  port: 8082
  servlet:
    context-path: '/ead-course/'


spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5434/ead-course
    username: eaduser
    password: eadpass
    driver-class-name: org.postgresql.Driver
  config:
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost