server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-course
    username: eaduser
    password: eadpass
    driver-class-name: org.postgresql.Driver
  config:
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
