version: '3.8'

services:
  postgres-course:
    image: postgres:15
    container_name: postgres-course
    restart: always
    environment:
      POSTGRES_USER: eaduser
      POSTGRES_PASSWORD: eadpass
      POSTGRES_DB: ead-course
    ports:
      - "5434:5432"
    volumes:
      - postgres_course_data:/var/lib/postgresql/data
    networks:
      - ead-network

volumes:
  postgres_course_data:

networks:
  ead-network:
    driver: bridge